### ISSUE TITLE
Size should apply movement modifiers

### ISSUE THREAD

**Issue by saif-ellafi** [Vendare/DarkHeresy2E-FoundryVTT#10]
The default value is 4 and comes in the sheets:
![image](https://user-images.githubusercontent.com/27952699/103228438-2224e300-4931-11eb-98bd-b5250d34363b.png)

But movement is read only

![image](https://user-images.githubusercontent.com/27952699/103228409-10434000-4931-11eb-836b-2f19f069944c.png)

**Comment by DerHarlekin921** [comment]
Same with some other traits:
Unnatural Agility, Quadruped, Sprint or the Flyer trait.

**Comment by Vendare** [comment]
Movement modifier due to size has been implemented
