### ISSUE TITLE
Edit menu in Notes does not open 

### ISSUE THREAD

**Issue by AndyTheMechanism** [Vendare/DarkHeresy2E-FoundryVTT#103]
the edit menu in Notes does not open. reinstalled the system. modules disabled

![image](https://user-images.githubusercontent.com/47814035/208313437-e238c3ef-79c0-4e4e-a6b0-e2571ac0b937.png)

**Comment by jangowolf** [comment]
I am having the same issue. Except i noticed it for actors notes.

Notes disappear but will reappear when i click the edit button.

Also when i try to I insert links to other actors, items, etc in the notes section it doesn't turn into a clickable link. It only displays as text.

**Comment by Dazzerix** [comment]
The actor and NPC sheet note issue is easily fixed. Go into the template file at dark-heresy/template/sheet/actor/tab/ notes and npc-notes respectively.
Go to near the bottom where you find "Enrichment.system.bio.notes" change to "content=system.bio.notes" and it works. 

Still trying to figure out if I can get item descriptions working.

**Comment by jangowolf** [comment]
> The actor and NPC sheet note issue is easily fixed. Go into the template file at dark-heresy/template/sheet/actor/tab/ notes and npc-notes respectively. Go to near the bottom where you find "Enrichment.system.bio.notes" change to "content=system.bio.notes" and it works.
> 
> Still trying to figure out if I can get item descriptions working.

That has fixed my problems for player notes an
![2022-12-26 23_04_07-Dark Phoenix Storm • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/51888805/209609478-01280b9c-b46d-495f-a5c6-213fcaf4b094.png)
![2022-12-26 23_04_03-Dark Phoenix Storm • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/51888805/209609479-7b22a6a3-b98d-443e-9553-69163e1353b4.png)
d not being able to link to other actors and items.

**Comment by MiguelWanderer** [comment]
Uff this Bug is driving me crazy :C
Guys any progress? Hint??

**Comment by Dazzerix** [comment]
For items the best I could do was add a new tab to the item sheets that has a insert box that adds text to the note box. It's an ugly solution, but it works for now while they fix the main issue.

Here's how to do it yourself if you want. In the dark heresy system folder: Go to template/sheet. You will find all item HTML's there for items. 

You are going to want to find the code that has the two central lines in this code. And add the 3rd line in this image. You can copy paste one of the other two lines and just change it. The important thing is the "data-tab="tempnotes". The white "temp notes" can be whatever you want to write. 

![Screenshot 2022-12-29 152515](https://user-images.githubusercontent.com/80884334/210020686-3df0a7f8-fbe1-45e5-b5f8-36a056af9b86.png)
`        <b class="item" data-tab="tempnotes">TEMP NOTES</b>` Figured out how to add code without this box using the code.

Then you just add this code after the notes tab. 

![Screenshot 2022-12-29 153453](https://user-images.githubusercontent.com/80884334/210021271-21a3ff59-9bbb-482f-b50a-2f77ce224384.png)
`<div class="tab" data-group="primary" data-tab="tempnotes">
            <div style="width 100%; height 132px">
                <label>Temporary notes. Fill here to fill out note section</label>
                <input name="system.description" type="text" value="{{system.description}}" />
            </div>
        </div>`

You'll have to make this edit for every single item type. But it works. It also works for psychic powers, just got to add an extra copy of both of those codes. And rename the data-tab to "tempeffects". The input also is different, it is system.effect instead of system.description.

**Comment by MiguelWanderer** [comment]
But doing that loses everything that was in the Notes?

**Comment by Dazzerix** [comment]
You need to ensure enrichment's been changed to content as well. I suppose I should've mentioned that.

**Comment by 1337scientist** [comment]
> Uff this Bug is driving me crazy :C Guys any progress? Hint??

Hey Miguel, came here to report the same bug. I found a workaround for the items, that might help for existing items. By posting them to the chat, the notes reappear:

![image](https://user-images.githubusercontent.com/96503593/211142601-99eebf60-a2c8-4597-a944-d57df60532f1.png)

Maybe that helps for the time beeing?

**Comment by Dazzerix** [comment]
I did actually figure out how to fix this bug. I know 3 slots of code were needed to do it, but I've been doing so much coding in this module now I dont remember if it was just those 3 things. If you want to put this in, back up your world and system module before hand. I'll also note I'm not actually one of the system developors. I'm just fixing things and adding new functions for my own group. 

script/common/sheet/actor/actor.js | Add this.
'  
async _enrichment() {
    let enrichment = {};
    enrichment["system.bio.notes"] = await TextEditor.enrichHTML(this.actor.system.bio.notes, {async: true});
    return expandObject(enrichment)
  }
  '
![Screenshot 2023-01-07 182419](https://user-images.githubusercontent.com/80884334/211177864-b3bec7d6-c230-4e68-9e09-eafdd206d243.png)


script/common/sheet/item.js | Add this.
` async _handleEnrichment(){
  let enrichment ={};
  enrichment["system.description"] = await TextEditor.enrichHTML(this.item.system.description, {async: true});
  enrichment["system.effect"] = await TextEditor.enrichHTML(this.item.system.effect, {async: true});
  return expandObject(enrichment)
}`

Same file: also change the get data function to this
`  async _enrichment() {
    let enrichment = {};
    enrichment["system.bio.notes"] = await TextEditor.enrichHTML(this.actor.system.bio.notes, {async: true});
    return expandObject(enrichment)
  }`
 
In script/common/handlebars.js | Make sure the register helper for text editor is either removed, or cancelled
`
//  Handlebars.registerHelper("enrich", function(string) {
//    return TextEditor.enrichHTML(string, {async: false});
// });
`
![Screenshot 2023-01-07 182440](https://user-images.githubusercontent.com/80884334/211177868-2b59c1ed-e250-4d33-a1e1-8213fee68e2c.png)

From there make sure all of the HTML files use the original editor formula. If you didn't try implementing my earlier suggestion, you'll be fine. 

`{{editor enrichment.system.description target="system.description" engine="prosemirror" button=true owner=owner editable=editable}}`

**Comment by DerHarlekin921** [comment]
Hey Dazzerix!

My files and filestructure look a bit different to what you posted.
I don't have a path "script/common/sheet/actor/actor.js" for example, but two others:
script/sheet/actor/actor.js and script/common/actor.js
The getData part of the file "script/sheet/actor/actor.js" looks like this:
![2023-02-07 13_06_02-D__Robert_Rollenspiele_Warhammer_40k_Allgemein_Data_systems_dark-heresy_script_s](https://user-images.githubusercontent.com/76706031/217240620-e7dc8e9f-62a6-41a5-a1dc-8c128b8eb82b.png)

I'm a bit confused if that is supposed to be like this? I have to say that I'm a total noob at programming and just finished a javascript basics course last week.

**Comment by MalishusJubes** [comment]
Dazzerix's notes are a little garbled but I managed to get the fix to work by following them. I only edited two files:

Local\FoundryVTT\Data\systems\dark-heresy\script\sheet\actor\actor.js
![ActorJsonFix](https://user-images.githubusercontent.com/127231064/223486792-f715b116-ae2a-474e-9f11-380c904e3eae.JPG)

Local\FoundryVTT\Data\systems\dark-heresy\script\sheet\item.js
![ItemJson](https://user-images.githubusercontent.com/127231064/223486811-09b11b0c-22d8-46f5-8bcc-fcb5be7bb5b2.JPG)

I hope this clarifies for anyone who was having any trouble. 

I've tested this on my local hosted backup but I have read that it may be better to use a module to add the functionality to the game system to smooth any future updates, does anyone have any insight on how to go about this?

**Comment by FilippoPolo** [comment]
Thanks @Dazzerix and @MalishusJubes , I've applied the fix and it works.

I'm just starting to learn how to develop FoundryVTT modules, and although I'm a decent JS developer, I've no familiarity with the API. If you feel like it, it would be really nice if you could explain why it was broken and what the fix is doing. :-)

WRT using a module, if it's a straight bug fix then IMHO it belongs in the system. I could make a PR?

**Comment by FilippoPolo** [comment]
By coincidence, I do automation too, but I also did some web stuff in the past. I don't know the Foundry API at all, though, so I'm wary of making PRs to this project.

For your problem, try this:
1) Open systems/dark-heresy/template.json
2) Find the object named "npc"
3) Add this property to the object:
```
      "bio": {
        "notes": ""
      },

```
Reload and let me know if it works.

**Comment by MalishusJubes** [comment]
> 1. Open systems/dark-heresy/template.json
> 2. Find the object named "npc"
> 3. Add this property to the object:
> 
> ```
>       "bio": {
>         "notes": ""
>       },
> ```
That did it, awesome, cheers mate

**Comment by bastiweb** [comment]
> 

You should really open up a pull request for that. It fixed the issue I tried to fix for like three hours (mind you I don't know s**t in JS).

**Comment by Vendare** [comment]
Fix Released to the Public
