### ISSUE TITLE
How to write characteristics correctly?

### ISSUE THREAD

**Issue by Levainen** [Vendare/DarkHeresy2E-FoundryVTT#106]
I don't understand how to write down the parameters of the character correctly. in Unnatural I write zero, in the Base I need the desired number, but in the end it is divided by 2 on the main screen. As a result, it also affects all skills. How does it work? 
![image](https://user-images.githubusercontent.com/15921692/208598212-f440f1e5-17d7-4dd1-98df-4e9beebba97a.png)

![2022-12-20_09-12-45](https://user-images.githubusercontent.com/15921692/208597662-31e38e4a-c11a-4d23-90a3-f6d354449e45.png)

**Comment by Vendare** [comment]
Set Fatigue to 0/7. Fatigue and wounds count up not down. The system automatically halves any characteristics whose bonus is lower than current fatigue

**Comment by Levainen** [comment]
> Set Fatigue to 0/7. Fatigue and wounds count up not down. The system automatically halves any characteristics whose bonus is lower than current fatigue
I'm an idiot, thanks for the help. Began to study the system. Missed this moment.
