### ISSUE TITLE
Auto-calc XP costs

### ISSUE THREAD

**Issue by FilippoPolo** [Vendare/DarkHeresy2E-FoundryVTT#114]
Hi all,

I've started working on a branch where actor sheets automatically calculate XP costs of advances, based on aptitudes. Aptitudes will be matched as strings, so users will need to spell them correctly (on the actor, and on talents) and also set a talent's tier correctly.

The behavior will be subject to an option, and the option will default to false, so existing sheets with custom costs won't be modified unexpectedly.

**Comment by FilippoPolo** [comment]
I've implemented this, and added a PR.

**Comment by Vendare** [comment]
Merged into Develop.
