### ISSUE TITLE
NPC Character Sheets Cannot Be Opened

### ISSUE THREAD

**Issue by Sinblade723** [Vendare/DarkHeresy2E-FoundryVTT#117]
Good Morning/Afternoon,

I have come across a bug that just started tonight on my end, for some reason I cannot access any NPC character sheets despite being the GM and all, nor can I even access any NPC sheets if I just create a new one as well, yet for some reason I can still access player character sheets with no issue the NPC sheets just never pop up no matter the method to bring them up.

Thank you for your time hope to hear from you!

**Comment by Vendare** [comment]
The Fix for the uneditable Notes on items and Actors had the unintended Sideeffect that new NPCs or NPCs that didn't receive any data in the notes Editor couldn't be opened Hotfix is going out.

**Comment by Sinblade723** [comment]
Thank you very much for your time and wonderful work on the module!
