### ISSUE TITLE
Combat Rolls for Semi-Auto and Full auto multiplying target BS by 100,000

### ISSUE THREAD

**Issue by KyleHaggin** [Vendare/DarkHeresy2E-FoundryVTT#124]
Performing a Semi-Auto shot when not Aiming and performing a Full-Auto shot in all situations causes issues with the target value calculation.
Semi-Auto sets the base target as BS x 100,000. Full-Auto sets the base target as (BS x 100,000 -100) and causes the Degrees of Failure to become NaN.
![Semi-Auto Bug](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/39069497/170c040d-bff7-440e-b8b5-8da012e1fcf9)
![Full-Auto Bug](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/39069497/5887081c-63db-471f-a259-b344e3dd9ed0)

Foundry and System version infomation.
![Version info](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/39069497/7548f275-cb62-4d9b-82d0-410a10c12501)

**Comment by KyleHaggin** [comment]
Further testing shows that semi-auto when aiming and/or with ranged bonuses and all standard shots always sets the target to BS+60 no matter what the the aim/range bonuses should be.

Semi-Auto with ranges
![Semi-auto bug range](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/39069497/bdf86e2e-90eb-4ed9-b740-4f4978bcaa86)
Semi-Auto with Aim
![Semi-auto bug aim](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/39069497/8a32fb25-b521-410f-b19c-e57f4215a66f)

Standard Shot with any combo
![standard shots](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/39069497/ec7dbac4-a99d-419d-934a-21be7b03840d)

**Comment by Vendare** [comment]
This happens because due to some Refactoring one of the value taken to calculate the Roll Target is a string instead of a number. Java Script being Javascript that is no problem leading to some funky looking numbers
