### ISSUE TITLE
Issues with the "dead" status icon

### ISSUE THREAD

**Issue by Tobytrooper** [Vendare/DarkHeresy2E-FoundryVTT#128]
"ActiveEffect validation errors: icon does not have a valid file extension" 

This message appears when I try to select the dead icon for actors. When looking in Condition lab it shows that the dead.png file isn't being selected for the dead status. 

![Thisbs](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/135565957/8879163d-5b39-433b-9087-41abe44278a4)

**Comment by Vendare** [comment]
Its missing the icons filename in the image path.

**Comment by Sage1700** [comment]
I managed to fix this locally in my ticket (#127) but I think this is something that needs to be looked at on the back side.

**Comment by Vendare** [comment]
Fixed with 4.2.6
