### ISSUE TITLE
Unsupported Core Version

### ISSUE THREAD

**Issue by aldaron838** [Vendare/DarkHeresy2E-FoundryVTT#130]
The game world is no longer launchable after Foundry's recent update to Version 11 Build 306

Error message when updating:
![image](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/33810839/80f2fbd6-bf25-49ec-873d-4af2eb789b2a)

Message when hovering the game world:
![image](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/33810839/3e717c70-010c-41fe-8770-88dc6a4726fc)

**Comment by Vendare** [comment]
Looks like the system manifest got corrupted. Uninstall then reinstall the system that should fix the problem

**Comment by aldaron838** [comment]
> Looks like the system manifest got corrupted. Uninstall then reinstall the system that should fix the problem

Seemed about right. A reinstall did the trick. Thank you!
