### ISSUE TITLE
Attack bonus in melee counted wrong.

### ISSUE THREAD

**Issue by Faultone** [Vendare/DarkHeresy2E-FoundryVTT#132]
In version 4.2.6 attack bonus in melee counted +10 higher than intended. Changing scripts/dark-heresy.json line # 1998: rollData.range = 10; to 0 worked for me, but I am not sure if it doesn't break something.

**Comment by Vendare** [comment]
Yeah that should have a qualifier before to only count when using Ranged weapons. Its used to set short range as the default range increment for ranged weapons. Fixed in Dev branch
