### ISSUE TITLE
[FEATURE REQUEST] Quicker reload method

### ISSUE THREAD

**Issue by reaperttt** [Vendare/DarkHeresy2E-FoundryVTT#136]
Currently, the only reload method I can find is to open the weapon and ammunition entries, then manually update every field. 

Suggestion: Drag and drop option from Ammunition to Weapon, which either replaces the details of the Weapon (if the Weapon/Name tags match), or possibly swaps them to conserve the ammo already in the gun.
Alternatively, maybe have the weapon linked to an Ammunition entry and remove the Remaining Clip entry?

**Comment by Vendare** [comment]
Linking Ammo and Weapons is a more complex task that is already covered with Issue #2. 
As a little quick fix the weapon can now be reloaded by clicking on the reload message. 
This only works for Linked Actors though.
