### ISSUE TITLE
Unable to edit parts of the character sheet

### ISSUE THREAD

**Issue by Doublemed** [Vendare/DarkHeresy2E-FoundryVTT#138]
I can seem to edit the values of the characteristics sections. Some sections are able to be edited while others arent.

**Comment by SirCracter** [comment]
Just to check, Doublemed, did you try to change the characteristics in the ADVANCES tab? I don't think you can adjust characteristics in the STATS tab, but you should be able to from the ADVANCES tab.

![image](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/97370889/dac85d86-6d76-4fad-a835-2318ee16f014)
