### ISSUE TITLE
Evasion test bug

### ISSUE THREAD

**Issue by BorisTheRazor** [Vendare/DarkHeresy2E-FoundryVTT#144]
When call the Evasion attack test from the result attack test chat message, test target value of Dodge/Parry skill displaed incorrectly (with bonuces from attack test - attack type, distance etc).
![image](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/75569530/79d6bc1e-f29a-4cb2-9be0-c43b41e4703a)

**Comment by Vendare** [comment]
Thats a problem with lacking seperation between types of rolls. The Calculation of a rolls Modifiers was done for every kind of roll in one function. This needs to be replaced with one function call for Combat Rolls and one for Skill or Characteristic Checks.
