### ISSUE TITLE
Add ability to change full-auto modifiers

### ISSUE THREAD

**Issue by Sebmaster777** [Vendare/DarkHeresy2E-FoundryVTT#146]
For those of us using previous versions of FFG products, being able to modify these values will be very convenient instead of needing to add/remove bonuses manually.

**Comment by Vendare** [comment]
That won't be implemented. Second Edition differs to much in the small details for it to support all other FFG-RPGs. 

1. Different Skills
2. Degrees of Success are counted differently
3. Righteous Fury works differently
4. Psychic Powers have been reworked
5. Different Attack Modifiers

Supporting all of that within the DH2E System would seriously hurt the maintainability of the System. It will only ever support the 2E Ruleset
