### ISSUE TITLE
Spray Weapon Ranges

### ISSUE THREAD

**Issue by kalain6** [Vendare/DarkHeresy2E-FoundryVTT#152]
The range of the cone template for a flame weapon is currently bugged in my experiance. I had to go into dark-heresy.js and change the following near line 2057
        rollData.range = !isMelee ? 10 : 0;
To:
        rollData.range = !isMelee ? weapon.range : 0;
in the
   static createWeaponRollData(actor, weapon) { } 
to get it to work properly.

**Comment by Vendare** [comment]
The template code is then not drawing from the correct variable. Rolldata.range is the modifier for the selected range band in combat.
