### ISSUE TITLE
Game wont load for me

### ISSUE THREAD

**Issue by AdmiralGrim** [Vendare/DarkHeresy2E-FoundryVTT#154]
Ever since the update I haven't been able to play the game. It keep saying unsupported core version. I'm not sure what to do here. Any help would be appreciated.

**Comment by Vendare** [comment]
The System has been updated for V11 unless you are using Foundry V11 you won't be able to launch into a World with the latest Release

**Comment by AdmiralGrim** [comment]
I do have the latest version of foundry, however the system still says unsupported

**Comment by Vendare** [comment]
have tried uninstalling and reinstalling the system ?
