### ISSUE TITLE
Chat Card Apply Wounds Issue

### ISSUE THREAD

**Issue by jayseaseven** [Vendare/DarkHeresy2E-FoundryVTT#156]
When applying wounds to a target via the chat card, it appears to automatically treat such wounds as Critical wounds, regardless of if a 10 were rolled, the damage exceeds current health, or any other factor. Tested on full-health tokens with high armor and toughness bonuses, and it still goes right to critical wounds. 
![image](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/73178576/2773eac3-be3c-4001-a5db-a5438579b967)

**Comment by Vendare** [comment]
Wounds count up not down if you set a Token to 12 / 12 Wounds he has no wounds left to soak. 
![image](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/6638899/b6c6834d-eaf1-4ec2-8a8e-5bf7f5a08945)
