### ISSUE TITLE
Storm Quality inacurate to rules as written for DH2E

### ISSUE THREAD

**Issue by CliffordH123** [Vendare/DarkHeresy2E-FoundryVTT#168]
The Storm quality is currently not properly implemented as it is currently ignoring the usual restrictions on number of hits that a weapon can gain.
The weapon quality states:

> Firing with a hail of shots, these weapons strike so rapidly that enemies are filled with metal in an instant. This quality doubles the number of hits the weapon inflicts on the target and the amount of ammunition expended. For example, when firing a weapon with the Storm quality in fully automatic mode, each degree of success yields two additional hits **_(up to the weapon’s firing rate, as normal)_**.

However in the current version a weapon with Storm quality and a Full Auto rate of fire 4 is capable of successfully hitting 8 times due to the way the Weapon Quality seems to functioning. Currently the Solution is to just put the shot numbers at half, but it would be nice if that wasn't neccesary. Especially since it means single fire option needs to be listed as .5 to work properly, with the same issue being present should you wish to homebrew any weapons with both the Storm Quality and Semi or Full Auto amounts that are odd numbers. And even this little trick isnt perfect as if we get enough degrees of success whilst the rate of fire is set to .5 the system still awards 2 or even 3 hits sometimes.

Example Provided:
![Storm Bolter Example](https://github.com/user-attachments/assets/9e93f0dd-f366-479d-a6d6-6c92e795f0b6)

![Storm Miscalculate](https://github.com/user-attachments/assets/343f0536-0aeb-4ce3-9113-fc5d13ae58f8)

**Comment by Vendare** [comment]
The wording there has always been a point of contention. When asked in the Errata of the Games with this exact wording the answer was always it can score maximum hits equal to double the rate of fire and that is how it is implemented.

**Comment by CliffordH123** [comment]
> The wording there has always been a point of contention. When asked in the Errata of the Games with this exact wording the answer was always it can score maximum hits equal to double the rate of fire and that is how it is implemented.

I see. I haven't found this in any of the pages of Second Edition FAQ v12. Which Errata are you referring to?

**Comment by Vendare** [comment]
![image](https://github.com/user-attachments/assets/833b31d2-cf0e-4d7a-bdc5-83b5c60b6721)
![image](https://github.com/user-attachments/assets/8935dbf4-4878-4c25-bef2-fc4f424bc451)
Rogue Trader for example way earlier in the game line exact same wording

Storm Weapons on Standard Attack fire 2 Bullets thus spending 2 Ammo and can score up to 2 Hits instead of one

**Comment by CliffordH123** [comment]
Okay gotcha your referencing the older TTRPGs for this. Works for me
