### ISSUE TITLE
[Feature Request] Support for backpacks-like items

### ISSUE THREAD

**Issue by Akeboshiwind** [Vendare/DarkHeresy2E-FoundryVTT#45]
Some bits of gear like Backpacks & Combat Vests or other bit of Gear that increases your encumbrance.

The workaround currently is just to add a negative weight for the gear, but it's a bit clunky as you have to subtract the weight of the item from the gained encumbrance.

It would be nice to have an "official" way to do this.

**Comment by Vendare** [comment]
duplicate of #3
