### ISSUE TITLE
When calculating armour value for a location, only use highest available armour value (armour is not additive)

### ISSUE THREAD

**Issue by aSemy** [Vendare/DarkHeresy2E-FoundryVTT#5]
Only one armour value should be used per location (the highest value). Armour should not stack. 

For example: two helmets stack to provide a armour value of 5, but it should be 4 (toughness bonus 2 + helmet armour value 2 = 4)

![image](https://user-images.githubusercontent.com/897017/102701360-99ce8000-4256-11eb-9a5e-75273b976f09.png)
![image](https://user-images.githubusercontent.com/897017/102701364-a226bb00-4256-11eb-9325-44fad96f288d.png)

- [ ] Fix actor.js `_computeArmour` to only use highest armour value per location (plus toughness bonus)
- [ ] Write a migration to recalcuate armour values

See CB pg 168, 'Mixing Armour'

**Comment by aSemy** [comment]
I think this code correctly calculates the max armour values.

```

    let maxArmourValues =
        data.items
        .filter(item => item.isArmour)
        .map(item => item.data.part)
        .reduce(function (accumulator, armourLocations) {
          Object.keys(armourLocations).forEach(function (key) {
            accumulator[key] = (accumulator[key] || 0) > armourLocations[key]
                ? accumulator[key] : armourLocations[key]
          })
          return accumulator;
        });

    data.data.armour.head.value = maxArmourValues["head"];
    data.data.armour.leftArm.value = maxArmourValues["leftArm"];
    data.data.armour.rightArm.value = maxArmourValues["rightArm"];
    data.data.armour.body.value = maxArmourValues["body"];
    data.data.armour.leftLeg.value = maxArmourValues["leftLeg"];
    data.data.armour.rightLeg.value = maxArmourValues["rightLeg"];
```

**Comment by DerHarlekin921** [comment]
Could this be made variable?
Some armours do in-fact stack, like Subskinarmour, Cranial armour or the added "toughness bonus" of cybernetic arms/legs. But also shields.

**Comment by luminousgrue** [comment]
Without some alternate way to adjust armor values to account for sources that _do_ stack - cybernetics, traits, Armor Monger etc - simply disabling stacking across the board is not a good fix here.

**Comment by Vendare** [comment]
Armour now has a flag that allows it to stack with each other
