### ISSUE TITLE
Dice Rolls, Fate, and Vengeful

### ISSUE THREAD

**Issue by LordKnightCecilo** [Vendare/DarkHeresy2E-FoundryVTT#61]
A number of issues that may be of benefit to the ability to play DH on Foundry.

1. It may be beneficial if you can click on the rolled items in the chatbox, to allow you to see the dice rolled for damage dice.

2. It may be beneficial if, like the WFRP4e Module, you can right click on a previously rolled item, and click to use a fate point to reroll the entire thing with the previous settings.

3. If possible, if would be beneficial if you could set the threshold for Righteous Fury per weapon, due to the nature of the Vengeful Special Rule. If not possible, the addition of the ability to see rolls as per the first suggestion, would still allow players to more easily know if they have triggered Righteous Fury.

Below are examples - 
DH2e Module:
![image](https://user-images.githubusercontent.com/8259916/122331103-45a11180-cf02-11eb-9b2b-384f333e5ed7.png)

DND5e Module:
![image](https://user-images.githubusercontent.com/8259916/122331207-72552900-cf02-11eb-99f2-342b8ab5b20a.png)

**Comment by Vendare** [comment]
Problems 1 and 3 have been implemented into the system.
Feature request 2 is still pending

**Comment by Vendare** [comment]
Added Context Option to reroll with fate
