### ISSUE TITLE
Size and Movement Speeds Incorrectly Calculated

### ISSUE THREAD

**Issue by luminousgrue** [Vendare/DarkHeresy2E-FoundryVTT#65]
Per table 4-6 on page 138, a character's Size modifies their movement speed. Size 4 is the baseline, and for every step up or down the character's AgB is modified by 1 for the purpose of calculating movement.

The module's character sheet correctly calculates movement speed base on AgB for a Size 4 character, but it appears to be applying the difference in Size as a flat change to all speeds. For instance a Size 4 character with an AgB of 4 has movement rates of 4/8/12/24 (this is correct), while a Size 8 character is shown as having rates of 8/12/16/28 on the sheet when (per rules reference) it _ought_ to be 8/16/24/48.

Additionally, there are traits and talents like Sprint and Quadruped that give flat modifiers to some movement rates - it would be useful to have the ability to override the auto-calculated movement speeds to keep track of these.

**Comment by Vendare** [comment]
Fixed a while ago, feature request handled in #76
