### ISSUE TITLE
Aptitude delete not working properly

### ISSUE THREAD

**Issue by saif-ellafi** [Vendare/DarkHeresy2E-FoundryVTT#7]
![asd](https://user-images.githubusercontent.com/27952699/102807065-48d99b80-43be-11eb-924f-8982bee8b6d2.gif)

**Comment by saif-ellafi** [comment]
Not sure if it helps but apparently the entry has been created as follows:
`"1608499995962":{"id":"1608499995963","name":"New Aptitude"}`

**Comment by aSemy** [comment]
Ah I've had that problem too! I though it was because two people were editing the same sheet simultaneously, but I couldn't reproduce it. Do you know what caused it?

**Comment by saif-ellafi** [comment]
Not really, I see in the code that the keys are based on timestamps, so could it be some update event? The whole thing works only if the key and the id value match, so it is a weird data structure overall

**Comment by aSemy** [comment]
I think Aptitudes should be re-written to be 'Items' that are in a compendium and can be dragged onto a char sheet. It's annoying having to type them out manually. Cooincidentally it should fix this bug. I'll try and get something set up.

**Comment by moo-man** [comment]
Are there a list of aptitude defined in the book? What are they for exactly.

**Comment by aSemy** [comment]
Yes, there's a set number of Aptitudes in the book - I think there are 19 in total. A character has a set of Aptitudes that essentially never change. They are determined at character generation (with one exception that I can think of), based from a character's homeworld and background. They are not used 'in action', only for determining the XP cost of levelling up or buying new abilities.

**Comment by moo-man** [comment]
That sounds appropriate for an Item, yeah.

**Comment by saif-ellafi** [comment]
I'd make sure that for homebrews and stuff perhaps let for custom ones?

**Comment by moo-man** [comment]
Not sure what you're saying @saif-ellafi , by making them items people can naturally add custom ones by creating them in their world..

**Comment by saif-ellafi** [comment]
Oh nevermind me. When they mentioned 19 items I thought it was going to be fixed to that.

They are used for leveling up and have nothing more than a name

**Comment by Vendare** [comment]
Has been fixed.
