### ISSUE TITLE
Separation of hit and damage rolls of attacks

### ISSUE THREAD

**Issue by 1337scientist** [Vendare/DarkHeresy2E-FoundryVTT#72]
Dear all,
would it be possible to separate the hit rolls of attacks from the damage roll?
The sequence we use in our games is hit - evasion - damage.
The way it is now, characters might decide to soak hits, because they see the damage result in advance. Or am I missing something?

Maybe it is possible to replace the automatic damage calculation with a button in the chat output, that can be clicked after evasions have been taken into account?

Thank you for your brilliant work though, it is so very much appreciated either way. 🙏

**Comment by Vendare** [comment]
Feature added in Dev
