### ISSUE TITLE
Experience calculator

### ISSUE THREAD

**Issue by Vaasimodo** [Vendare/DarkHeresy2E-FoundryVTT#75]
Hi. 

I was wondering if there is an issue/bug with the experience calculating? 

If I type a number in the 'Current' tab and add a skill/talent ect. it is adding those exp up to the total tab.
So if current is'n the total amount of exp you earned over the time, you only can put your current available  exp in there and need to manually substract the amount of epx cost for the next skill/talent ect. 
Is that the way it's supposed to be?
If yes the total spent tab would be useless? 

I think the issue here is, that all exp from the skills ect adds up to the total amount of exp and this makes no sense?

Pls help :) 
Maybe it's my fault and I do something wrong. I just want to understand where the issue is.

**Comment by Vendare** [comment]
The calculation is weird. The current XP are your unspent xp. This is about to change if my PR is approved. The current field will be renamed total on the sheet and the user enters the total experience the character has. Unpent will be shown as 'remeining'

**Comment by Vendare** [comment]
Experience has been reworked this problem has been solved
