### ISSUE TITLE
'Configure Default token Settings' is overridden by the system.

### ISSUE THREAD

**Issue by TomChristoffer** [Vendare/DarkHeresy2E-FoundryVTT#78]
Dark Heresy 2e overrides the settings inputted in the default token settings under the core settings tab, resetting token disposition to neutral, name to 'hovered by owner' and resources to 'hovered by owner' with no resources selected. This also happens when duplicating another actor.

**Comment by Vendare** [comment]
The system sets these once upon creation and then never again. The Defaults have been fixed with #105
