### ISSUE TITLE
v10 Manifest missing `id` field

### ISSUE THREAD

**Issue by rikmarais** [Vendare/DarkHeresy2E-FoundryVTT#83]
Hi there 👋 
Nothing major here but the [manifest](https://raw.githubusercontent.com/moo-man/DarkHeresy2E-FoundryVTT/master/system.json) is missing the v10 `id` field specified in https://foundryvtt.com/article/manifest-migration-guide/
As such, it may fail certain migration or compatibility checks that rely on this field being present.

**Comment by rawocd** [comment]
I just tried to update to v10 and v4.0 and am getting an error that 4.0 doesn't supposed v10 build 290(or any other v10 build i can try through forge.  Is this missing id field why I am getting that error?

**Comment by rikmarais** [comment]
> I just tried to update to v10 and v4.0 and am getting an error that 4.0 doesn't supposed v10 build 290(or any other v10 build i can try through forge. Is this missing id field why I am getting that error?

That's likely the case, yes. You can download the release as a zip file, copy the the `name` field in the `system.json` and rename it to `id`, and then upload the module as a custom package through the Forge's Import Wizard to fix it.

**Comment by rawocd** [comment]
Just as a follow up for this, the above suggestion does indeed work if you are running into issues with forge's compatibility checker.
