### ISSUE TITLE
Ammo Item type Issue

### ISSUE THREAD

**Issue by jayseaseven** [Vendare/DarkHeresy2E-FoundryVTT#86]
It appears as though Ammo Item Types cannot be updated successfully with new images. Every other item works as intended, but attempting to alter ammo does not update item image or item name. Other fields update when changed.
![image](https://user-images.githubusercontent.com/73178576/199868862-fe65a334-2923-4915-875d-caf7ff1faf30.png)

edit: didn't see the pull request, but that's the issue

**Comment by TheGiddyLimit** [comment]
(Closed by #84 )
