### ISSUE TITLE
Make actions draggable into the hotbar

### ISSUE THREAD

**Issue by saif-ellafi** [Vendare/DarkHeresy2E-FoundryVTT#9]
It would be nice to be able to drag & drop actions like Ballistic Skills or any of the skills into the hotbar for shortcut.

At the moment, unless for custom macros, there's no integration of the system into it.

**Comment by aSemy** [comment]
From what I can tell, only Items (such as weapons, psychic powers, equipment) can be dragged and dropped at all - skills and characteristics cannot. From testing in the DnD5e module they have allowed Items (e.g. weapons and abilities) to be dragged and dropped into the macro bar to automatically create a macro

An alternative would be to create a macro named 'Strength test'. This would roll Strength of any selected character. This macro could be saved into a compendium and shared with the DH2e module. 

The downside is that the modifier couldn't be changed before the roll is done, so the chat message might say 'Success! Degree of Success: 1' even if you imagined a modifier of -60. I'd actually like to change our tests so instead of a separate pop-up there's a message in the chat log (to determine the target and difficulty etc). The macro would trigger this pre-roll chat log message.

**Comment by aSemy** [comment]
Here's an example macro. 


![image](https://user-images.githubusercontent.com/897017/103831752-0af69b80-507d-11eb-9641-148b7d5ece3e.png)

```javascript
if (canvas.tokens.controlled.length === 0) {
  ui.notifications.info("Strength Test: No token selected")
}

canvas.tokens.controlled
.filter((token) => {
let type = token.actor?.data?.type
return "acolyte" === type || "npc" === type
})
.forEach((token) => {
let actor = token.actor
const skill = actor.data.data.characteristics["strength"];
let rollData = {
  name: skill.label,
  baseTarget: skill.total,
  modifier: 0
}
game.darkHeresy.commonRoll(rollData)
})
```


First, use the select tool to select one (or more) tokens. Then left click on the macro.

Upon doing this I realise we need to improve the chat messages. They don't specify which character is rolling, which means it's really unclear if multiple characters roll something at once!

![image](https://user-images.githubusercontent.com/897017/103832047-b43d9180-507d-11eb-8959-f72efa882479.png)

**Comment by saif-ellafi** [comment]
Btw, I have here a generic rolling dice Macro:

```
function _getDegree(a, b) {
  return Math.floor(a / 10) - Math.floor(b / 10);
}
let confirmed = false;
new Dialog({
  title: "Manual Dice Roller",
  content: `<p>Enter target value</p><form><div class="form-group"><input id="target_value" type="text" placeholder="e.g. 30"><select id="modifiers">
  <option value="-20">-20</option>
  <option value="-10">-10</option>
  <option value="+0" selected>+0</option>
  <option value="+10">+10</option>
  <option value="+20">+20</option>
  <option value="+30">+30</option>
  </select></div><input id="desc_value" type="text" placeholder="Description?"><div></div></form>`,
  buttons: {
    go: { label: "Continue", callback: () => confirmed = true },
    cancel: { label: "Cancel", callback: () => confirmed = false }
  },
  close: html => {             
    if (confirmed) {
      let entered = html.find('#target_value').val().trim() + html.find('#modifiers').val();
      let entered_desc = html.find('#desc_value').val().trim() + " ";
      if (!entered) return ui.notifications.error(`Nothing was entered, skipping.`);
      let calculated = new Roll(entered).roll().total;
      let roll = new Roll(`1d100`).roll();
      let degrees = _getDegree(calculated, roll.result);
      let result = degrees < 0 ? `<span style="color:red">Failure</span>` : `<span style="color:green">Success</span>`;
      roll.toMessage({
        user: game.user._id,
        speaker: ChatMessage.getSpeaker({token: actor}),
        content: `<div class="dice-roll">
          <div class="dice-result">
            <div class="dice-formula">${entered_desc}<b>| Target: ${calculated} |</b></div>
            <div class="dice-tooltip">
              <section class="tooltip-part">
                <div class="dice">
                  <header class="part-header flexrow">
                    <span class="part-formula">1d100 vs ${entered}</span>
                    <span class="part-total">${roll.total}</span>
                  </header>
                  <ol class="dice-rolls">
                    <li class="roll die d100">${roll.total}</li>
                  </ol>
                </div>
              </section>
            </div>
          <h4 class="dice-total">${result} (${roll.total}) Do${degrees < 0 ? 'F' : 'S'}: ${Math.abs(degrees)+1}</h4>
              </div>
          </div>`
      });
    };
  },
  default: "go"
}).render(true);
```

**Comment by Nosferaschu** [comment]
I could use the Strenght test macro and modified it so i could use it for characteristics and skills.
But could some one give me an example for items. like Laspistol. 
Or even better is there coming the drag and drop option for items in an update?

**Comment by Nosferaschu** [comment]
I figured it out my self, for those who want to use items with macros, here are 2 examples for weapons and psy powers
Weapon
`if (canvas.tokens.controlled.length === 0) {
  ui.notifications.info("No token selected")
}

canvas.tokens.controlled
.filter((token) => {
  let type = token.actor?.data?.type
  return "acolyte" === type || "npc" === type
})
.forEach((token) => {
  let actor = token.actor
  const skill = actor.data.data.characteristics["weaponSkill"];
  let item = actor.data.items.find(item => item.flags.core.sourceId === "Item.PaxZyJu3RPtJhF4J"); //ID fürs source item

	if (item.data.class === "melee"){
		var isrange = 0;
		var ismelee = 1;
	} else {
		var isrange = 1;
		var ismelee = 0;
	}
	let rollData = {
		wid: item._id,
		name: item.name,
		baseTarget: skill.total,
		modifier: 0,
		psy:  {value: actor.data.data.psy.rating, max: actor.data.data.psy.rating},
		damageFormula: item.data.damage,
		damageType: item.data.damageType,
		damageBonus: 0,
		penetrationFormula: item.data.penetration,
		isRange: isrange,
		isMelee: ismelee,
		clip: {value: item.data.clip.value, max: item.data.clip.max},
		rateOfFire: {burst: item.data.rateOfFire.burst, full: item.data.rateOfFire.full}
	}
	game.darkHeresy.prepareCombatRoll(rollData,actor)
})`

Psy powers
`if (canvas.tokens.controlled.length === 0) {
  ui.notifications.info("No token selected")
}

canvas.tokens.controlled
.filter((token) => {
  let type = token.actor?.data?.type
  return "acolyte" === type || "npc" === type
})
.forEach((token) => {
	let actor = token.actor
  let item = actor.data.items.find(item => item.flags.core.sourceId === "Item.uhJuAh2KW0ePniAm"); //ID fürs source item

	let rollData = {
		wid: item._id,
		name: item.name,
		baseTarget: actor.data.data.characteristics["willpower"].total,
		modifier: item.data.focusPower.difficulty,
		psy:  {value: actor.data.data.psy.rating, max: actor.data.data.psy.rating},
		damageFormula: item.data.damage.formula,
		damageType: item.data.damageType,
		damageBonus: 0,
		penetrationFormula: 0,
		attackType: {name: item.data.damage.zone},			
	}
	game.darkHeresy.preparePsychicPowerRoll(rollData)
})`

the sourceId can be found if you look in the items.db or the better looking way, export the character and find the item in the json file.

**Comment by Nosferaschu** [comment]
The 2 Macro Types above do not work anymore, if someone has an idea why, pls let me know =)

**Comment by Vendare** [comment]
Weapons and Psychic Powers can now be drag 'n' dropped onto the Hotbar to create Macros for rolling them
