### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by Sinblade723** [Vendare/DarkHeresy2E-FoundryVTT#99]
Hello!

I wished to inform while using recently and updating from the previous version it seems the weapon types (mostly ranged weapons) and Psyker powers are not able to be rolled or used anymore.

When players or myself click them they allow you to set up the actions and all but upon clicking "Roll" never actually roll or show up on the text log or anything of the sorts after migrating over to the newer version despite them working in the last one.

Was not aware if you knew of this and figured this was the place to put it, thank you very much and have a great day!

**Comment by Vendare** [comment]
Made a little mess while resolving merge conflicts works now with new release 4.0.3
